# Se introduce el token de acceso adquirido en el registro o en el login
GET http://localhost:4000/api/dashboard
x-token-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3OTBkMjg5NC03NzE2LTQ4MTgtYWE1MC0wMWZlYmZhZGQzOWUiLCJpYXQiOjE2NDE5MjU2MTUsImV4cCI6MTY0MTkzMjgxNX0.Pzv9pcuTWWiB6USUVZnWPsfVCz7njfGGkzGph9m1Zaw